class Constants {
  static const loremIpsum =
      """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer enim metus, ultricies a ultrices a, facilisis non lacus. Aenean sed tortor nulla. Morbi auctor venenatis dui at malesuada. Aliquam suscipit nunc et tortor bibendum aliquet auctor mollis ligula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et accumsan lorem, quis consequat est. Praesent suscipit urna id pellentesque ullamcorper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus consequat, velit in tincidunt tristique, nulla justo vehicula massa, venenatis pharetra libero eros eu odio. Vivamus sollicitudin ex sit amet est gravida, eu sodales ipsum vulputate. Nulla fermentum nibh sit amet consequat porttitor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam accumsan, tellus non dictum rutrum, ante quam maximus odio, nec euismod nisl diam vitae ex. Morbi gravida arcu odio, sed congue dui euismod non.

In hac habitasse platea dictumst. Donec aliquet non lectus vel sodales. Cras odio orci, vulputate at ullamcorper eu, dictum vel mi. Donec dictum consequat leo a viverra. Vestibulum eget lorem erat. Phasellus non eleifend libero. Pellentesque auctor lacus et nibh interdum, non eleifend lorem molestie. Mauris dapibus risus elementum ipsum iaculis, vitae accumsan nisl tempus. Aenean ut ligula sed risus ultrices venenatis. Suspendisse rhoncus viverra nisi maximus maximus. Ut lacus magna, condimentum nec justo vitae, blandit euismod purus.

Integer ornare fringilla tortor, sit amet dignissim leo ultrices et. Aenean in enim eget nunc aliquam condimentum. Integer eu facilisis elit. Etiam ut dolor id enim accumsan imperdiet. Aliquam lobortis congue mi, ac interdum ipsum ultrices non. Nunc vulputate, nulla id venenatis tempus, odio risus tristique purus, eu egestas odio nulla egestas nisi. Phasellus faucibus enim non ornare tincidunt.

Praesent in egestas elit. Fusce interdum quam purus, eu imperdiet magna vehicula vel. Aliquam a nibh at arcu aliquam tincidunt. Cras sollicitudin auctor enim, vel posuere diam fringilla sed. Morbi volutpat ipsum neque, eget euismod augue tincidunt et. Cras rhoncus odio sed neque dignissim volutpat. Donec congue mauris urna, nec dapibus lacus ullamcorper quis.

Quisque vel rutrum justo. Maecenas lorem nisi, porttitor et tincidunt sed, efficitur eu eros. Morbi faucibus diam augue, vel consequat neque rhoncus ut. Phasellus tempus at mauris elementum auctor. Ut justo mauris, luctus quis elementum sit amet, aliquam a turpis. Sed accumsan varius ligula, semper condimentum urna consectetur eu. In bibendum at nisl non accumsan. Pellentesque nec rutrum lorem. Cras vitae aliquam ante, a fringilla erat. Duis venenatis lacinia nibh vitae posuere. """;
}
